spring:
  application.name: IvTurBotApp
  main.banner-mode: off
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    jooq:
      sql-dialect: PostgreSQL
    hikari:
      maximum-pool-size: 5

  sql:
    init:
      mode: always

telegram.bot:
  username:
  token:
logging:
  level:
    root: INFO
    org:
      jooq: DEBUG
      jooq.Constants: WARN
